### ISSUE TITLE
Size in bytes

### ISSUE THREAD

**Issue by rodrigopolo** [deoxxa/node-mediainfo#2]
Is there anyway to get each size value in bytes instead of MiB, GiB, etc.?

**Comment by deoxxa** [comment]
I added filesize-parser to get an approximation of the filesize in bytes - I'm not sure if mediainfo itself has options for displaying the raw size. There are a bunch of options for mediainfo, and I'll probably look at supporting them a bit better (or at all), but for now this should do the trick (I hope!).

**Comment by rodrigopolo** [comment]
I wrote to Jerome Martinez <jerome AT mediaarea DOT net> about a way to get all raw data on XML or JSON and even proposed a format http://sourceforge.net/p/mediainfo/discussion/297610/thread/ed58d0f6#0fd7/1259

After that he sent me more information:

> this would be a very specific request, more development, but maybe what already exists is enough for you.
> Try with:
> mediainfo -f --Language=raw --Output=XML FileName
> 
> If you need only data for computers, you can do:
> mediainfo -f --Language=raw --Output=XML --ReadByHuman=0 FileName
> 
> You will see file size in bytes, duration in milliseconds...

So I modified your code adding those flags and adding some options to the execFile function to handle the huge amount of data returned when a M4V contain a JPEG or XML embeded as Base64 making the returned string on stdout huge:

``` js
  child_process.execFile("mediainfo", [
      '-f', 
      '--Language=raw', 
      '--Output=XML', 
      '--ReadByHuman=0'
    ].concat(files),{ 
      encoding: 'utf8',
      maxBuffer: 20*(1024*1024)
    }, function(err, stdout, stderr) { /* ... */ });
```

BTW I'm raising money to get $300 for Jerome and have a native JSON output just as the XML output works :D

**Comment by rodrigopolo** [comment]
I created a module for this purpose:
https://github.com/rodrigopolo/mimovie
