### ISSUE TITLE
Receive ony error on MAC

### ISSUE THREAD

**Issue by simar88** [deoxxa/node-mediainfo#3]
Hi @deoxxa i'm using mediainfo on Mac Os X with node.js but i receive always:
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
Do you any suggestion?

**Comment by timonsku** [comment]
You probably provided an invalid media file path

**Comment by metaory** [comment]
same error on arch linux

**Comment by mbarzda** [comment]
mediainfo: https://mediaarea.net/lt/MediaInfo/Download should be installed. Solved.

**Comment by deoxxa** [comment]
Yep, that's documented.
